version: '3.8'

services:
  api01: &api
    image: rinha:latest
    hostname: api01
    volumes:
      - db:/usr/src/db
    ports:
      - '3000:3000'
    environment:
      - port=3000
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '250MB'

  # api02:
  #   <<: *api
  #   hostname: api02
  #   ports:
  #     - '3001:3001'
  #   environment:
  #     - port=3001

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '150MB'

volumes:
  db:

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
